[GLOBAL]
pants_version = "2.26.0"
backend_packages.add = [
  "pants.backend.python",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = false

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["src"]

[python]
interpreter_constraints = ["==3.13.*"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}

[python-bootstrap]
search_path = ["<PYENV>"]