"""initial

Revision ID: 7ced9fef83a3
Revises:
Create Date: 2025-12-25 11:26:34.333100

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ced9fef83a3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_game_time", sa.JSON(), nullable=True),
        sa.Column("end_game_time", sa.JSON(), nullable=True),
        sa.Column("recurrence", sa.JSON(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("regional_variations", sa.JSON(), nullable=True),
        sa.Column("faction_specific", sa.Boolean(), nullable=False),
        sa.Column("affected_factions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("seasonal", sa.Boolean(), nullable=False),
        sa.Column("related_world_memories", sa.ARRAY(sa.UUID()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendar_months",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("month_number", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("history", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cultural_significance", sa.JSON(), nullable=True),
        sa.Column("regional_variations", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_months_month_number"), "calendar_months", ["month_number"], unique=True
    )
    op.create_table(
        "calendar_year_cycles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cycle_year", sa.Integer(), nullable=False),
        sa.Column("animal_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("animal_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("traits", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("cultural_significance", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_year_cycles_cycle_year"),
        "calendar_year_cycles",
        ["cycle_year"],
        unique=True,
    )
    op.create_table(
        "character_classes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("emoji", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "character_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("abbr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("emoji", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_value", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_mutable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "episode_memories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("one_sentence_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("key_moments", postgresql.ARRAY(sa.JSON()), nullable=True),
        sa.Column("relationships_changed", sa.JSON(), nullable=True),
        sa.Column("themes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("cliffhangers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("characters", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("locations", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("session_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("importance_score", sa.Float(), nullable=True),
        sa.Column("promoted_to_world", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_episode_memories_expires_at"), "episode_memories", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_episode_memories_promoted_to_world"),
        "episode_memories",
        ["promoted_to_world"],
        unique=False,
    )
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_characters_per_player", sa.Integer(), nullable=False),
        sa.Column("max_game_sessions", sa.Integer(), nullable=False),
        sa.Column("max_players_per_game_session", sa.Integer(), nullable=False),
        sa.Column("max_game_session_idle_duration", sa.Integer(), nullable=False),
        sa.Column("game_channel_slowmode_delay", sa.Integer(), nullable=False),
        sa.Column("game_time_enabled", sa.Boolean(), nullable=False),
        sa.Column("game_time_multiplier", sa.Float(), nullable=False),
        sa.Column("game_hours_per_day", sa.Integer(), nullable=False),
        sa.Column("game_days_per_year", sa.Integer(), nullable=False),
        sa.Column("game_day_start_hour", sa.Integer(), nullable=False),
        sa.Column("game_night_start_hour", sa.Integer(), nullable=False),
        sa.Column("game_epoch_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("game_time_persistence_interval_minutes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_time",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_game_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("game_year", sa.Integer(), nullable=False),
        sa.Column("year_day", sa.Integer(), nullable=False),
        sa.Column("game_month", sa.Integer(), nullable=True),
        sa.Column("game_day", sa.Integer(), nullable=True),
        sa.Column("cycle_year", sa.Integer(), nullable=True),
        sa.Column("game_hour", sa.Integer(), nullable=False),
        sa.Column("game_minute", sa.Integer(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("day_of_week", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_daytime", sa.Boolean(), nullable=False),
        sa.Column("time_multiplier", sa.Float(), nullable=False),
        sa.Column("epoch_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_shutdown_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("game_time_config", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("emoji", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_categories_name"), "item_categories", ["name"], unique=True)
    op.create_table(
        "memory_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_memory_expiration_hours", sa.Integer(), nullable=False),
        sa.Column("episode_memory_expiration_hours", sa.Integer(), nullable=False),
        sa.Column("snapshot_retention_days", sa.Integer(), nullable=False),
        sa.Column("auto_cleanup_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("snapshot_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_data", sa.JSON(), nullable=True),
        sa.Column("world_memory_id", sa.Uuid(), nullable=True),
        sa.Column("episode_id", sa.Uuid(), nullable=True),
        sa.Column("created_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("can_unwind", sa.Boolean(), nullable=False),
        sa.Column("unwound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unwound_by", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_snapshots_episode_id"), "memory_snapshots", ["episode_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_snapshots_world_memory_id"),
        "memory_snapshots",
        ["world_memory_id"],
        unique=False,
    )
    op.create_table(
        "npcs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("race", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("background", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("profession", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("faction", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("effects", sa.JSON(), nullable=True),
        sa.Column("renown", sa.Integer(), nullable=False),
        sa.Column("shadow_level", sa.Integer(), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_health", sa.Float(), nullable=False),
        sa.Column("max_health", sa.Float(), nullable=False),
        sa.Column("current_stamina", sa.Float(), nullable=False),
        sa.Column("max_stamina", sa.Float(), nullable=False),
        sa.Column("current_tech_power", sa.Float(), nullable=False),
        sa.Column("max_tech_power", sa.Float(), nullable=False),
        sa.Column("current_armor", sa.Float(), nullable=False),
        sa.Column("max_armor", sa.Float(), nullable=False),
        sa.Column("is_incapacitated", sa.Boolean(), nullable=False),
        sa.Column("last_resource_update", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tasks", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "world_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_conditions", sa.JSON(), nullable=True),
        sa.Column("end_conditions", sa.JSON(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_game_time", sa.JSON(), nullable=True),
        sa.Column("end_game_time", sa.JSON(), nullable=True),
        sa.Column("recurrence_pattern", sa.JSON(), nullable=True),
        sa.Column("regional_scope", sa.JSON(), nullable=True),
        sa.Column("related_world_memories", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("impact_level", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("affected_factions", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "world_memories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("memory_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_narrative", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("related_entities", sa.JSON(), nullable=True),
        sa.Column("source_episodes", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("consequences", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("impact_level", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("discovery_requirements", sa.JSON(), nullable=True),
        sa.Column("related_world_event_id", sa.Uuid(), nullable=True),
        sa.Column("related_world_item_id", sa.Uuid(), nullable=True),
        sa.Column("regional_context", sa.JSON(), nullable=True),
        sa.Column("game_time_context", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_world_memories_impact_level"), "world_memories", ["impact_level"], unique=False
    )
    op.create_index(
        op.f("ix_world_memories_is_public"), "world_memories", ["is_public"], unique=False
    )
    op.create_table(
        "world_regions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("region_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parent_region_id", sa.Uuid(), nullable=True),
        sa.Column("hierarchy_level", sa.Integer(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("locations", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("factions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("custom_boundaries", sa.JSON(), nullable=True),
        sa.Column("active_events", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("regional_variations", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_region_id"],
            ["world_regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "character_class_stats",
        sa.Column("character_class_id", sa.Uuid(), nullable=False),
        sa.Column("character_stat_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_class_id"],
            ["character_classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_stat_id"],
            ["character_stats.id"],
        ),
        sa.PrimaryKeyConstraint("character_class_id", "character_stat_id"),
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("exp", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("effects", sa.JSON(), nullable=True),
        sa.Column("inventory", sa.JSON(), nullable=True),
        sa.Column("equipped_items", sa.JSON(), nullable=True),
        sa.Column("renown", sa.Integer(), nullable=False),
        sa.Column("shadow_level", sa.Integer(), nullable=False),
        sa.Column("current_health", sa.Float(), nullable=False),
        sa.Column("max_health", sa.Float(), nullable=False),
        sa.Column("current_stamina", sa.Float(), nullable=False),
        sa.Column("max_stamina", sa.Float(), nullable=False),
        sa.Column("current_tech_power", sa.Float(), nullable=False),
        sa.Column("max_tech_power", sa.Float(), nullable=False),
        sa.Column("current_armor", sa.Float(), nullable=False),
        sa.Column("max_armor", sa.Float(), nullable=False),
        sa.Column("is_incapacitated", sa.Boolean(), nullable=False),
        sa.Column("last_resource_update", sa.DateTime(timezone=True), nullable=True),
        sa.Column("character_class_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_class_id"],
            ["character_classes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=True)
    op.create_table(
        "encounters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("game_session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "encounter_type",
            sa.Enum("COMBAT", "SOCIAL", "ENVIRONMENTAL_HAZARD", name="encountertype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "ABANDONED", name="encounterstatus"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dead_npcs", sa.JSON(), nullable=True),
        sa.Column("rewards_distributed", sa.Boolean(), nullable=False),
        sa.Column("searched_npcs", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_encounters_game_session_id"), "encounters", ["game_session_id"], unique=False
    )
    op.create_table(
        "game_history_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("game_session_id", sa.Uuid(), nullable=False),
        sa.Column("history_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_history_embeddings_game_session_id"),
        "game_history_embeddings",
        ["game_session_id"],
        unique=False,
    )
    op.create_table(
        "item_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("equippable_slots", sa.JSON(), nullable=True),
        sa.Column("rarity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("stat_bonuses", sa.JSON(), nullable=True),
        sa.Column("stat_multipliers", sa.JSON(), nullable=True),
        sa.Column("resource_bonuses", sa.JSON(), nullable=True),
        sa.Column("resource_regeneration_modifiers", sa.JSON(), nullable=True),
        sa.Column("damage_bonuses", sa.JSON(), nullable=True),
        sa.Column("damage_multipliers", sa.JSON(), nullable=True),
        sa.Column("healing_bonuses", sa.JSON(), nullable=True),
        sa.Column("inventory_slots_bonus", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["item_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_templates_name"), "item_templates", ["name"], unique=True)
    op.create_table(
        "location_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("location_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("facts", sa.JSON(), nullable=True),
        sa.Column("connections", sa.JSON(), nullable=True),
        sa.Column("travel_requirements", sa.JSON(), nullable=True),
        sa.Column("physical_properties", sa.JSON(), nullable=True),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("constraints", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["world_regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_location_facts_location_name"), "location_facts", ["location_name"], unique=False
    )
    op.create_table(
        "npc_memories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("npc_id", sa.Uuid(), nullable=False),
        sa.Column("memory_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["npc_id"],
            ["npcs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_npc_memories_npc_id"), "npc_memories", ["npc_id"], unique=False)
    op.create_table(
        "character_class_starting_equipment",
        sa.Column("character_class_id", sa.Uuid(), nullable=False),
        sa.Column("item_template_id", sa.Uuid(), nullable=False),
        sa.Column("equipment_slot", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_class_id"],
            ["character_classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_template_id"],
            ["item_templates.id"],
        ),
        sa.PrimaryKeyConstraint("character_class_id", "item_template_id"),
    )
    op.create_table(
        "character_quests",
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("quest_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["quests.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "quest_id"),
    )
    op.create_table(
        "character_recognition",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("known_character_id", sa.Uuid(), nullable=False),
        sa.Column("first_met_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_interaction_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("known_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("known_details", sa.JSON(), nullable=True),
        sa.Column("relationship_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("trust_level", sa.Float(), nullable=True),
        sa.Column("shared_episodes", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["known_character_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "known_character_id", name="uq_character_known_character"
        ),
    )
    op.create_index(
        op.f("ix_character_recognition_character_id"),
        "character_recognition",
        ["character_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_character_recognition_known_character_id"),
        "character_recognition",
        ["known_character_id"],
        unique=False,
    )
    op.create_table(
        "encounter_characters",
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.PrimaryKeyConstraint("encounter_id", "character_id"),
    )
    op.create_table(
        "encounter_npcs",
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("npc_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["npc_id"],
            ["npcs.id"],
        ),
        sa.PrimaryKeyConstraint("encounter_id", "npc_id"),
    )
    op.create_table(
        "game_session_characters",
        sa.Column("game_session_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("game_session_id", "character_id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("discord_id", sa.BigInteger(), nullable=True),
        sa.Column("global_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("active_character_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["active_character_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_discord_id"), "players", ["discord_id"], unique=True)
    op.create_table(
        "session_memories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("memory_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.Column("participants", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("importance_score", sa.Float(), nullable=True),
        sa.Column("emotional_valence", sa.Float(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_memories_character_id"), "session_memories", ["character_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_memories_processed"), "session_memories", ["processed"], unique=False
    )
    op.create_index(
        op.f("ix_session_memories_session_id"), "session_memories", ["session_id"], unique=False
    )
    op.create_table(
        "world_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("item_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("collection_condition", sa.JSON(), nullable=True),
        sa.Column("collected_by", sa.Uuid(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at_game_time", sa.JSON(), nullable=True),
        sa.Column("collection_session_id", sa.Uuid(), nullable=True),
        sa.Column("quest_goals", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("location_hint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("regional_availability", sa.JSON(), nullable=True),
        sa.Column("faction_origin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("related_world_memories", sa.ARRAY(sa.UUID()), nullable=True),
        sa.ForeignKeyConstraint(
            ["collected_by"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collection_session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_session_players",
        sa.Column("game_session_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("game_session_id", "player_id"),
    )
    op.create_table(
        "gm_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("game_session_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=True),
        sa.Column("action_character", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("characters", sa.JSON(), nullable=True),
        sa.Column("request", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_messages", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gm_history_game_session_id"), "gm_history", ["game_session_id"], unique=False
    )
    op.create_table(
        "player_characters",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "character_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_characters")
    op.drop_index(op.f("ix_gm_history_game_session_id"), table_name="gm_history")
    op.drop_table("gm_history")
    op.drop_table("game_session_players")
    op.drop_table("world_items")
    op.drop_index(op.f("ix_session_memories_session_id"), table_name="session_memories")
    op.drop_index(op.f("ix_session_memories_processed"), table_name="session_memories")
    op.drop_index(op.f("ix_session_memories_character_id"), table_name="session_memories")
    op.drop_table("session_memories")
    op.drop_index(op.f("ix_players_discord_id"), table_name="players")
    op.drop_table("players")
    op.drop_table("game_session_characters")
    op.drop_table("encounter_npcs")
    op.drop_table("encounter_characters")
    op.drop_index(
        op.f("ix_character_recognition_known_character_id"), table_name="character_recognition"
    )
    op.drop_index(op.f("ix_character_recognition_character_id"), table_name="character_recognition")
    op.drop_table("character_recognition")
    op.drop_table("character_quests")
    op.drop_table("character_class_starting_equipment")
    op.drop_index(op.f("ix_npc_memories_npc_id"), table_name="npc_memories")
    op.drop_table("npc_memories")
    op.drop_index(op.f("ix_location_facts_location_name"), table_name="location_facts")
    op.drop_table("location_facts")
    op.drop_index(op.f("ix_item_templates_name"), table_name="item_templates")
    op.drop_table("item_templates")
    op.drop_index(
        op.f("ix_game_history_embeddings_game_session_id"), table_name="game_history_embeddings"
    )
    op.drop_table("game_history_embeddings")
    op.drop_index(op.f("ix_encounters_game_session_id"), table_name="encounters")
    op.drop_table("encounters")
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_table("characters")
    op.drop_table("character_class_stats")
    op.drop_table("world_regions")
    op.drop_index(op.f("ix_world_memories_is_public"), table_name="world_memories")
    op.drop_index(op.f("ix_world_memories_impact_level"), table_name="world_memories")
    op.drop_table("world_memories")
    op.drop_table("world_events")
    op.drop_table("skills")
    op.drop_table("quests")
    op.drop_table("npcs")
    op.drop_index(op.f("ix_memory_snapshots_world_memory_id"), table_name="memory_snapshots")
    op.drop_index(op.f("ix_memory_snapshots_episode_id"), table_name="memory_snapshots")
    op.drop_table("memory_snapshots")
    op.drop_table("memory_settings")
    op.drop_index(op.f("ix_item_categories_name"), table_name="item_categories")
    op.drop_table("item_categories")
    op.drop_table("game_time")
    op.drop_table("game_settings")
    op.drop_table("game_sessions")
    op.drop_index(op.f("ix_episode_memories_promoted_to_world"), table_name="episode_memories")
    op.drop_index(op.f("ix_episode_memories_expires_at"), table_name="episode_memories")
    op.drop_table("episode_memories")
    op.drop_table("character_stats")
    op.drop_table("character_classes")
    op.drop_index(op.f("ix_calendar_year_cycles_cycle_year"), table_name="calendar_year_cycles")
    op.drop_table("calendar_year_cycles")
    op.drop_index(op.f("ix_calendar_months_month_number"), table_name="calendar_months")
    op.drop_table("calendar_months")
    op.drop_table("calendar_events")
    # ### end Alembic commands ###
